backend:
  name: github
  repo: stuut/netlify-cms-tutorial

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: category, label: Category, widget: list }
